### ISSUE TITLE
Error in sample.int(m, k) :  cannot take a sample larger than the population when 'replace = FALSE'

### ISSUE THREAD

**Issue by xiaotong-666** [FloWuenne/scFunctions#10]
Hi scFunctions Developer,

Nice package for doing this.
when i am trying to determine thresholds using our k-means function, R is always throwing a strange error. 

For example, I got an error while I tried to do that:
kmeans_thresholds <- auc_thresh_kmeans(regulonAUC) 

Error in sample.int(m, k) : 
cannot take a sample larger than the population when 'replace = FALSE'

How can i solve this problem?
I sincerely hope i can get your help!
Thanks

**Comment by FloWuenne** [comment]
Hi @xiaotong-666,

thanks for the nice comments! This is actually just a small collection of scripts I used for myself but I hoped they might be useful for others as well.

Just right upfront, if you are still using the old R pipeline with SCENIC, I would recommend switching to the nextflow workflows that the SCENIC authors now offer. They are much easier to run and more reproducible:
https://github.com/aertslab/SCENICprotocol
or
https://github.com/vib-singlecell-nf/vsn-pipelines
Unfortunately, I haven't had time to update my tutorial here to use the output from these new pipelines... 

Regarding your question for the auc_thresh_kmeans function, I would need a bit more information. Can you share part of your input data? What is the size of your input regulonAUC? Can you make sure that your AUCs are not all 0 for the data you are testing? 

If you can, please let me know some more details and I am happy to help!
