### ISSUE TITLE
error calculate_csi

### ISSUE THREAD

**Issue by paolo-kunderfranco** [FloWuenne/scFunctions#11]
Hi,

I have a problem in the first step of calculates_csi:

```
> regulonAUC<-readRDS("int/3.4_regulonAUC.Rds")
> regulons_csi <- calculate_csi(regulonAUC = regulonAUC,calc_extended = TRUE)
Error in regulonAUC@assays$data : 
  $ operator not defined for this S4 class
```

`> str(regulonAUC)
Formal class 'aucellResults' [package "AUCell"] with 6 slots
  ..@ nGenesDetected : num(0) 
  ..@ colData        :Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : chr [1:21171] "WT_CD_1_AAACCTGCAGCTATTG" "WT_CD_1_AAACCTGCATCGATGT" "WT_CD_1_AAACCTGTCAGGCGAA" "WT_CD_1_AAACCTGTCCAGAAGG" ...
  .. .. ..@ nrows          : int 21171
  .. .. ..@ listData       : Named list()
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ assays         :Formal class 'SimpleAssays' [package "SummarizedExperiment"] with 1 slot
  .. .. ..@ data:Formal class 'SimpleList' [package "S4Vectors"] with 4 slots
  .. .. .. .. ..@ listData       :List of 1
  .. .. .. .. .. ..$ AUC: num [1:505, 1:21171] 0.0575 0.0409 0.1002 0.0903 0.0649 ...
  .. .. .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. .. .. ..$ gene sets: chr [1:505] "Nfia_extended (76g)" "Nfia (39g)" "Sirt6_extended (34g)" "Klf13_extended (21g)" ...
  .. .. .. .. .. .. .. ..$ cells    : chr [1:21171] "WT_CD_1_AAACCTGCAGCTATTG" "WT_CD_1_AAACCTGCATCGATGT" "WT_CD_1_AAACCTGTCAGGCGAA" "WT_CD_1_AAACCTGTCCAGAAGG" ...
  .. .. .. .. ..@ elementType    : chr "ANY"
  .. .. .. .. ..@ elementMetadata: NULL
  .. .. .. .. ..@ metadata       : list()
  ..@ NAMES          : chr [1:505] "Nfia_extended (76g)" "Nfia (39g)" "Sirt6_extended (34g)" "Klf13_extended (21g)" ...
  ..@ elementMetadata:Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 505
  .. .. ..@ listData       : Named list()
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
  ..@ metadata       : list()`

Any suggestion?

best
Paolo

**Comment by FloWuenne** [comment]
Hi @paolo-kunderfranco ,

thank you for posting the issue. I hope I can help you figure this out! 
I tested the function with the test data that I provided in /example_data/regulonAUC_subset.Rds and it seems to work fine with this dataset. 

I suspect this could be due to different versions of AUCell or SCENIC, or potentially be related to your input data. 
Let's start some simple tests to see what we can find out. What is returned if you try this in R: 
`regulonAUC@assays$data`

From your error message with the calculate_csi function, I would expect `regulonAUC@assays$data` to return an error as well!!

**Comment by paolo-kunderfranco** [comment]
Thanks a lot for your fast reply: 

`regulonAUC@assays$data
Error in regulonAUC@assays$data : 
  $ operator not defined for this S4 class`

and here is my sessionInfo,

`R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /home/pkunderfranco/.conda/envs/Scenic_scFunctions/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2     doMC_1.3.7             iterators_1.0.13       doRNG_1.8.2           
 [5] rngtools_1.5           foreach_1.5.1          RcisTarget_1.10.0      AUCell_1.12.0         
 [9] SCopeLoomR_0.10.1      loomR_0.2.1.9000       hdf5r_1.3.3            R6_2.5.0              
[13] Seurat_3.2.2           scFunctions_0.0.0.9000 forcats_0.5.0          stringr_1.4.0         
[17] dplyr_1.0.2            purrr_0.3.4            readr_1.4.0            tidyr_1.1.2           
[21] tibble_3.0.4           ggplot2_3.3.2          tidyverse_1.3.0        SCENIC_1.2.2     `

**Comment by FloWuenne** [comment]
Ok, so it's probably what I expected from the error in the function.
 
I think for some reason your AUCell rds object is different than the one I wrote the function for. This could be related to some changes in the version of AUCell or SCENIC... 

The easiest way to help is if I could try with your AUCell rds object to troubleshoot to be honest. Would it be possible to share the AUC rds object with me somehow?

**Comment by paolo-kunderfranco** [comment]
Hi,

Have you had a chance to look to the data I shared with you?

Which version of AUCell is recommended to run completely scFunctions?

Best
Paolo

**Comment by FloWuenne** [comment]
Hi @paolo-kunderfranco,

The function should be working with any AUCell version. I was just thinking that the authors might have changed the way the data is organized inside an AUCell object at some point after I wrote the function... I can check whether this is the case once I have a look at your object.

I didn't receive any data from you? How did you try to share it?

**Comment by paolo-kunderfranco** [comment]
try with this

https://drive.google.com/file/d/1w7QO7XmtRW41k84NF-J_vucFx6dp2Lxs/view?usp=sharing

**Comment by FloWuenne** [comment]
Thank you so much. I am so sorry, I actually just found your email wit the data link as well in my emails. I completely missed this when you initially send it. 

I just had a look and I think I fixed your issue. The issue was that in my function, the data was stored in :

`regulonAUC@assays$data@listData$AUC` 

whereas now it seems that this changed to

`regulonAUC@assays@data@listData$AUC`

I updated the function calculate_csi and tested with your object and it worked on my machine. I hope that it will work for you as well after i have pushed the changes and you reinstall the package! 

Best,

Florian

**Comment by FloWuenne** [comment]
Please let me know whether it is working after you have reinstalled scFunctions and  I will close this issue afterward. :)

**Comment by FloWuenne** [comment]
I also realized that this is exactly an issue that @zktuong had fixed in some functions with his pull request (#9). Guess I should have checked in the past pull requests and would have found the fix quicker... ;)!

**Comment by paolo-kunderfranco** [comment]
perfect, thanks, now is working properly!

Best
paolo
