### ISSUE TITLE
gskb package end of life

### ISSUE THREAD

**Issue by GildasLepennetier** [FloWuenne/scFunctions#12]
Trying to install with the fresh R version 4.1.0 (2021-05-18) returns an error concerning the gskb package dependency.

`devtools::install_github("FloWuenne/scFunctions")`
`ERROR: dependency ‘gskb’ is not available for package ‘scFunctions’`

BiocManager::install("gskb") does not help since the package is apparently now **deprecated** [see link](http://bioconductor.org/packages/release/data/experiment/html/gskb.html)

**Comment by FloWuenne** [comment]
Hi @GildasLepennetier , 

sorry to hear you had issues with the installation on a new R build.

I made a branch where I completely removed the gskb package and commented that the function using it is deprecated. 

Maybe you can try:

`devtools::install_github("FloWuenne/scFunctions", ref = "remove_gskb")`

to see if this installs on your new machine?

Thanks for the issue!

**Comment by GildasLepennetier** [comment]
Hi Flo!
It does install using this branch, indeed. Thanks for the reactivity!
This was no big problem since I am sourcing the functions, just wanted you to have an up-to-date package ;)
I will close the issue.
