### ISSUE TITLE
Error in calculate_rrs

### ISSUE THREAD

**Issue by ShaowenJ** [FloWuenne/scFunctions#3]
Hi scFunctions Developer,

Nice package for doing this.
But in the tutorial, I think you missed the code for calculating the RSS.
Nevertheless, I got an error while I tried to do that:
rrs_df <- calculate_rrs(cellInfo,binary_regulons, cell_type_column = "seuratCluster")

Error in binary_regulons[regulon, ] : incorrect number of dimensions

cellInfo is the metadata table from seurat

Thanks!

**Comment by GildasLepennetier** [comment]
Do you actually have rownames in your binary_regulons?

**Comment by FloWuenne** [comment]
Hi @Lesdormis,

sorry for the very let reply! You are totally right and I did forget to put the code for calculating the rrs. I will add this very soon and add a very short tutorial on how to process results from the new SCENIC nextflow pipeline, as this makes it much easier to produce SCENIC results from single-cell data than the R implementation:

In the meantime, you can check out:
[SCENICprotocol](https://github.com/aertslab/SCENICprotocol)

and this notebook where they also calculate rrs:
https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.ipynb
